### ISSUE TITLE
can't parse formula('sumif(……)')

### ISSUE THREAD

**Issue by AdamWangDoggie** [python-excel/xlwt#106]
I used xlwt to write a formula like 
`wst2.write(x,y,xlwt.Formula('sumif(page!D:D,1,page!E:E)'),TextStyle)`
It came to:
`Traceback (most recent call last):
  File "C:\Users\11507137\Desktop\02 OEM共享\日报汇总\bina\runner.py", line 38, in <module>
    date1).replace("-", "."), str(date2).replace("-", "."))
  File "C:\Users\11507137\Desktop\02 OEM共享\日报汇总\bina\config.py", line 346, in write
    supplier, currentdate, date1, date2)
  File "C:\Users\11507137\Desktop\02 OEM共享\日报汇总\bina\config.py", line 323, in write
    wst2.write(5+i,1,xlwt.Formula('sumif(代工费内!D:D,%s,代工费内!E:E)'% (catedict[catename[i]]+1)),TextStyle)
  File "C:\Users\11507137\AppData\Local\Programs\Python\Python35-32\lib\site-packages\xlwt\ExcelFormula.py", line 22, in __init__
    raise ExcelFormulaParser.FormulaParseException("can't parse formula " + s)
xlwt.ExcelFormulaParser.FormulaParseException: can't parse formula sumif(代工费内!D:D,1,代工费内!E:E)`

Could you solve this?
thx.

**Comment by jdufresne** [comment]
Can you provide a minimal example script to reproduce? If required to reproduce, please also provide an xls document. Thanks.

**Comment by Leezj9671** [comment]
@jdufresne This is the same question as mine. See #136

**Comment by jdufresne** [comment]
From @Leezj9671 in #136 

> When I tried to use `table.write(3, 7, xlwt.Formula("CORREL(C:C,F:F)"))`, it raised error 
> ```
> File "D:\conda\lib\site-packages\xlwt\ExcelFormula.py", line 22, in __init__
>     raise ExcelFormulaParser.FormulaParseException("can't parse formula " + s)
> xlwt.ExcelFormulaParser.FormulaParseException: can't parse formula CORREL(C:C,F:F)
> ```
> But formula like `CORREL(C2:C389,F2:F389)` works. Can you add the feature to support `CORREL(C:C,F:F)`?

**Comment by jdufresne** [comment]
Instead of a single line, can you provide a full test script that produces the error? Something that I can run: `python test.py` on to see the error? Thanks.

**Comment by Leezj9671** [comment]
@jdufresne 
```python
import xlwt
import xlrd
from xlutils.copy import copy

wb = xlwt.Workbook()
sheet = wb.add_sheet('sheet1')
sheet.write(0, 0, 1.977817343)
sheet.write(1, 0, 1.922536174)
sheet.write(0, 1, 12.17326194)
sheet.write(1, 1, 10.91212935)
wb.save('test.xls')

rexcel = xlrd.open_workbook('test.xls')
excel = copy(rexcel)
table = excel.get_sheet(0)
# It raised error
#table.write(0, 2, xlwt.Formula('SUM(A:A,B:B)'))
# It works
table.write(0, 2, xlwt.Formula('SUM(A1:A2,B1:B2)'))
excel.save('test_new.xls')
```
